### PR TITLE
Mile-stone 6:  Building with Responsive design

### PR DESCRIPTION
**Pull request by enaburekhan**
**The clone of The Next web.com by Dibyendu Das and Eric Enaburekhan.**
In this project:

- We design for mobile, tablet, and desktop size screen to ensure the site is responsive.
- Use flex-box, grid, and float properties for positioning.
- Use media queries to separate the tablet and desktop version from the mobile version

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I can see you worked hard on this project but I am sorry to inform you that I cannot Approve this project because it is not completed yet.😟
_It's okay. We are here to learn. Don't get discouraged. Work more hard. You are there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Please remove validation errors. 

- [ ] main navigation row and sub-navigation row are not aligned. Please have a look at the original website. 

- [ ] On medium and small screens the logo is stretched and not aligned properly
chrome-capture (34)

- [ ] Please add TNW logo here as present in original page
chrome-capture (35)

- [ ]  Text is not properly aligned please work on it 
chrome-capture (36)

- [ ] This is not  how it looks like on original page. Please work on it
chrome-capture (38)

- [ ] use orignal logo TNW not text or any other logo here
chrome-capture (39)


- [ ] **Optional** In the whole webpage the images are strched please make them perfect as in original page.


- [ ]  Your footer is different than the original one. Please have a look 
**ORIGINAL**
chrome-capture (33)
**Yours **
chrome-capture (32)


- [ ] **Optional** Please try to add your screenshot in assets/images. That would be great.
chrome-capture (30)

- [ ] **Optional** Please correct this mistake from your readme file
chrome-capture (40)


**Please make the changes and request re-review for the given project**
Stay safe😇

### Happy Coding
-------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by enaburekhan** [comment]
**Code review comments changes effected for both required and optional**:

- Fix navigation rows.
- Replace the logo on the nav section.
- Align text on the header section.
- Replace text with the original TNW logo in footer section.
- Fix image size.
- Fix footer color.

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## Hello :wave: Team!! I've seen you have made some improvements from the past review.

:100: Descriptive README!!
:100: Improved the footer

There are still some requested changes that still remain to fix. Please review the last requested changes and review this next check list.

### [Mandatory]

- [ ] The project has issues rendering on the mobile version. the with of the smallest container is bigger than the smallest screen.

- [ ] The navbar in mobile version still is not working properli
image

- [ ] The hamburger is not showing in mobile version.
image

- [ ] Some areas in mobile version are overlapping.
image

- [ ] Latter news section is not displaying correctly in mobile desing.
image

- [ ] Funding section not displayin correctly in mobile desing.
image

- [ ] Mobile version, overall, is not looking as it should
image

- [ ] Nav bar does not match original in desktop version
image

- [ ] Areas are not changing accordingly to the original responsive design.
image

- [ ] The links in the footer don't have space between them.
image

### [COMMENTS]

- [ ] Review responsiveness for each section individually. To help with this issue, use the web developer tools that come with every browser most of them open with ```CTRL+Shift+I``` and use the Media Query Inspector.

Keep up the great work :muscle:, and Happy Coding :smiley: :computer: !!

**Comment by enaburekhan** [comment]
**Review comments feedback:**

- The project renders perfectly on mobile screen. Pls check your browser settings:

mobile-session

- The navbar works perfectly. Check your browser settings.
nav-bar

- The Hamburger shows clearly in the mobile sessions.Check your browser settings.

hamburger

- The Mobile version text well aligned and not overlapping as claimed. Check your browser settings.

mobile-text

- The funding session perfectly displayed in the mobile session. Check your browser settings.

funding

- The mobile version was carefully done and looks very much like the original website. Check your browser settings.

- The desktop navbar was carefully designed and looks very much like the original. Check your browser settings.

desktop-nav

- The areas are very responsive in both my partner and my browser. Pls check your browser settings.

areas-responsive

- The footer was carefully designed and looks perfectly like the original. Check your browser settings.

footer

**Review by teekaytech — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @enaburekhan & @dibdas :wave: 

### Awesome job so far. However, there are some changes that require fixing before this project can be approved.

**Before we start, I want you to understand that the main point of this project is to implement a Responsive Web Design, and that is why the previous TSEs have been focusing on this aspect during their code review.**

Let's start!

- [ ] From my observation, you're having a horizontal scroll bar on your page. This is affecting the way your page is rendering on different screen sizes. Kindly find the source of this horizontal scroll bar and have it removed.

- [ ] Check the images below. Please pay close attention to the screen sizes on top of the images and the placement of the TNW logo. Compare your page with the original page and make changes as necessary.

Navbar from Original Page (size 760px)

s

Navbar from your page (same size)

y

- [ ] There seems to be some overlapping of texts on small screen sizes (300px). You can possibly avoid this by reducing the font size of those concerned texts for small screen sizes. See the images below for clarification.

App section from original page (300px)

o

App section from your page (same screen size)

y

- [ ] Work on your navbar paddings and margins for medium screen sizes.

Original page: 

o

Your page: 

y

- [ ] Your footer seems to be changing as the breakpoint changes. Kindly adjust your footer so it doesn't change on breakpoints.




Your footer: (at 1024px)

y

Original footer: (same width)

o


I hope you can spot the differences from those images. Just take your time to closely observe the main website. You've already structured the page, all you have to do now is to ensure that all the finishing touches are taken care of.

Kindly make these changes and request for another review.

I'm available on slack (@taofeekolalere) if you need further clarification.
Happy Coding :man_technologist:

**Comment by enaburekhan** [comment]
Code review comments effected:

- Fix footer section. screen shot @ 1280px:

footer-1280

- Fix the horizontal scroll bar. 
- App session well displayed on the mobile sessions. I recommend you display with iphone 6/7/8.

appsession

- The navbar for the medium screen is well displayed. I recommend checking with the original iPad.

navbar med

- This project was designed for responsiveness using **iPhone 6/7/8, original iPad size, and normal desktop size.**

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @dibdas AND 

Good job with the changes! :tada: We are almost there.
**Please make sure the required changes by previous changes. Thanks**
##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

### Navbar
- [ ] Fix text  alignment the Navbar on Large screen

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/dibdas/Building-with-Responsive-Design/feature-responsive/index.html)|
|:---:|:---:|
|orginial-nav-large|clone-nav-large|
- [ ] Fix Logo and text  alignment the Navbar on 990px

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/dibdas/Building-with-Responsive-Design/feature-responsive/index.html)|
|:---:|:---:|
|o-nav-990|c-nav-990|
##
- [ ] Fix Logo and text  alignment the Navbar on 760px

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/dibdas/Building-with-Responsive-Design/feature-responsive/index.html)|
|:---:|:---:|
|o-nav-760|c-nav760|
##

### Header
- [ ] Text is not properly aligned (on 790px) please work on it

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/dibdas/Building-with-Responsive-Design/feature-responsive/index.html)|
|:---:|:---:|
|o-text-790|c-text-790|

##

### Footer
- [ ] Text is not properly aligned (on 992px) please work on it

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/dibdas/Building-with-Responsive-Design/feature-responsive/index.html)|
|:---:|:---:|
|o-footer992|c-footer-992|

##

- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by enaburekhan** [comment]
**Code review comments effected:**

- Fix text-alignment on navbar on large screen.
- Fix logo and text-alignment on navbar at 990px.
- Fix logo and text-alignment on navbar at 760px
- Align text at 760px.
- Align text at 790px.
- Align footer text at 992px.

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :sunglasses: Great Improvement!! :100: the code has improved and does not present most of the issues above mention! Awesome!!! :clap: :clap: 

The project has some issues unresolved. Please work on them.

### [Mandatory]

- [ ] As commented in pasts reviews Navbar doesn't match mobile style.

image

### [OPTIONAL]

- [ ] Missing whitespace... The same object that are before this one does have the margin-top/padding-top

image

## Keep up the great work :muscle: and Happy Coding :smiley: :computer: !!!

**Comment by enaburekhan** [comment]
**Code review changes effected:**

- Replace the mobile session navbar logo
- Fix the missing white space

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED 🍾  🎉 🚀

Hello team great work on the project and also on implementing the changes required by the previous TSE
I will go ahead and mark this as complete, feel free to merge when you are ready

## ❗ Before Merging [required]:

tnw

- [ ] On the large screen there is a TNW logo on the featured article. Please take a look at the screenshot above. 

## [Optional]

- [ ] Increase the font-size of the headings of the feature articles to match the screenshot above.

- [ ] There is an overlay on the feature article: a linear-gradient background can do the trick. example `background: linear-gradient( to left bottom, rgba(151, 18, 18, 0.8) 10%, rgba(0, 0, 0, 0.8) 60%, rgba(0, 0, 0, 1) )...`


### Cheers and Happy coding! 👏

#### Code review by Uduak Essien
(Feel free to contact me on slack(@acushla), if you have any additional question)

**Pull request merged**
